import streamlit as st

st.title("Terms of Use – PortIQ")
st.markdown(
    """
_Last updated: October 2025_

Welcome to **PortIQ** (“we,” “us,” “our”). By accessing or using this application (the “App”), you agree to these Terms of Use.

---

### 1. Educational Purpose Only
PortIQ is an **educational and informational tool** that generates sample investment portfolios using artificial intelligence.  
It **does not provide investment, financial, legal, or tax advice**, and nothing in the App should be interpreted as such.  
You should consult a licensed financial advisor before making investment decisions.

---

### 2. No Client Relationship
Use of the App **does not create an advisor–client relationship** between you and PortIQ or its developers.  
We are **not registered as a broker, dealer, or investment adviser** under U.S. securities laws.

---

### 3. Accuracy and Limitations
Outputs are generated by machine-learning models and public market data sources.  
While we attempt to ensure accuracy, PortIQ **makes no warranties or guarantees** about the completeness, reliability, or accuracy of any information produced.  
All content is provided “as-is” and “as available.”

---

### 4. User Responsibilities
You agree not to:
- Use the App for unlawful, malicious, or fraudulent purposes.
- Enter personally identifiable or confidential financial information.
- Attempt to reverse engineer, copy, or resell the service without written permission.

---

### 5. Intellectual Property
All software, prompts, models, and branding of PortIQ are owned by the developers and protected by intellectual-property laws.  
You are granted a limited, non-exclusive, revocable license to use the App for educational purposes.

---

### 6. Limitation of Liability
To the fullest extent permitted by law, PortIQ, its owners, and affiliates **shall not be liable** for any direct, indirect, incidental, or consequential damages arising from use of the App or reliance on its outputs.

---

### 7. Indemnification
You agree to indemnify and hold harmless PortIQ and its affiliates from any claims, losses, or expenses (including attorneys’ fees) arising from your use of the App or violation of these Terms.

---

### 8. Modifications
We may update or modify these Terms at any time. Continued use of the App after such changes constitutes acceptance of the revised Terms.

---

### 9. Governing Law
These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict-of-law principles.

---

If you have questions about these Terms, contact us at **support@portiq.ai**.
"""
)


